eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
logging:
  level:
    root: INFO
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
server:
  port: 8201

