#注册中心
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

info:
  name: marvel-gateway
  organization: org.marvel
  build:
    version: 1.0.0

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: marvel-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

feign:
  hystrix:
    enabled: false

zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin